version: "3.9"
services:
  mqtt_cpp_broker:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 8884:8884
      - 9001:9001
    expose:
      - '8884'
      - '9001'
    volumes:
      - type: bind
        source: ./mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
  mqtt_cpp_pub:
    build: "./mqtt_pub"
    expose:
      - '8884'
    volumes:
      - type: bind
        source: ./mqtt_pub
        target: /home
  mqtt_cpp_sub:
    build: "./mqtt_sub"
    expose:
      - '8884'
    volumes:
      - type: bind
        source: ./mqtt_sub
        target: /home